# Default values for csvserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



#Values for csvserver deployment
replicaCount: 1

csvserver:
  repository: infracloudio/csvserver
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

env_csv:
  name: CSVSERVER_BORDER
  value: Orange

ports_csv:
  containerPort: 9300

app: csvserver

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 9300
  targetport: 9300
  nodePort: 30000

#Values for Prometheus deployment
prometheus:
  repository: prom/prometheus
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

  containerPort: 9090
  
  service:
    type: NodePort
    port: 9090
    targetport: 9090
    nodePort: 30001

  global:
    scrape_interval: 15s
    evaluation_interval: 15s
