apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-svc
  labels:
    {{- include "prometheus.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.targetport }}
      nodePort: {{ .Values.prometheus.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "prometheus.selectorLabels" . | nindent 4 }}
