apiVersion: v1
data:
  prometheus.yml: |
        global:
          scrape_interval: {{ .Values.prometheus.global.scrape_interval }}
          evaluation_interval: {{ .Values.prometheus.global.evaluation_interval }}
        scrape_configs:
          - job_name: 'prometheus'
            static_configs:
            - targets: ['localhost:9090', '{{ .Release.Name }}-csvserver-svc:9300']
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-prometheus-cm
